
TOPDIR = ..

HOST_TARGET = pnmtohex

# Modern distro's (e.g. Debian, Fedora Core) seem to have -lnetpbm only
#LIBS += -lnetpnm -lnetpbm -lnetpgm -lnetppm
#LIBS += -L./ -lnetpbm

include $(TOPDIR)/Rules.make

